#!/bin/bash

if [[ -n "$TZ" ]]; then
  echo "$TZ" > /etc/timezone
fi

chown backup:backup /etc/proxmox-backup
chmod 700 /etc/proxmox-backup

echo "API: Starting..."
exec /usr/lib/aarch64-linux-gnu/proxmox-backup/proxmox-backup-api
